#!/bin/sh

set -e

DESC="filebrowser"
NAME=filebrowser
DAEMON=/usr/bin/$NAME
ARG="-a 0.0.0.0 -b /files -r /DataVolume -d /DataVolume/.filebrowser.db --cache-dir /CacheVolume/filebrowser"

case "$1" in
  start)
        echo -n "Starting $DESC: "
        start-stop-daemon -S -b -x $NAME -- $ARG
        echo "OK"
        ;;
  stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon -K -x $NAME
        echo "OK"
        ;;
  restart|force-reload)
        echo "Restarting $DESC: "
        $0 stop
        sleep 1
        $0 start
        echo ""
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac
                            
exit 0             
